name: Build and Deploy to Cloud Run

# 1. Build React Frontend
# 2. Move Build Folder into Server
# 3. Dockerize Server

on:
  push:
    branches:
      - "testing"
      - "production"

env:
  PROJECT_ID: bert-aug2022-359622
  GAR_LOCATION: us-central1
  BRANCH: ${GITHUB_REF##*/}
  SERVICE: bert
  REGION: us-central1

jobs:
  deploy:

    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:

      - name: Deploy Testing
        if: 'testing' == ${{ env.BRANCH }}
        env:
          NODE_ENV: testing
        run:
          echo "Setting up Testing Environment"

      - name: Deploy Production
        if: 'production' == ${{ env.BRANCH }}
        env:
          NODE_ENV: production
        run:
          echo "Setting up Production Environment"

      - name: Checkout
        uses: actions/checkout@v3

      - id: auth
        name: Google Authentication
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}
