name: Build and Deploy to Cloud Run

# 1. Build React Frontend
# 2. Move Build Folder into Server
# 3. Dockerize Server

on:
  push:
    branches:
      - "testing"
      - "production"

env:
  PROJECT_ID: bert-aug2022-359622
  GAR_LOCATION: us-central1
  BRANCH: ${GITHUB_REF##*/}
  SERVICE: bert
  REGION: us-central1

jobs:

  deploy:
  
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - id: auth
        name: Google Authentication
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}
          
      - uses: 'docker/login-action@v1'
        with:
          registry: ${{ env.REGION }}-docker.pkg.dev
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
      
      - name: Build and Push Container
        run: |-
          docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ env.BRANCH }}:latest" ./
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ env.BRANCH }}:latest"
          
