name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - testing

env:
  PROJECT_ID: bert-aug2022-359622
  GAR_LOCATION: us-central1
  REPOSITORY: bert
  SERVICE: testing
  REGION: us-central1

jobs:
  deploy:

    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}' # e.g. - projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}' # e.g. - my-service-account@my-project.iam.gserviceaccount.com

      # Authenticate Docker to Google Cloud Artifact Registry
      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v1'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'
          
      - name: Build and Push Container
        run: |-
          docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}" ./
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}"
      # END - Docker auth and build

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
    

      - name: Deploy to Cloud Run
        id: deploy
        run: >
          gcloud run deploy testing-bert
          --quiet
          --region ${{ env.REGION }}
          --image ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}
          --platform managed
          --service-account my-service-account@bert-aug2022-359622.iam.gserviceaccount.com
          --allow-unauthenticated
          --set-env-vars "NODE_ENV=production"
          --set-env-vars "MONGO_USER=${{ secrets.TESTING_MONGO_USER }}"
          --set-env-vars "MONGO_PASS=${{ secrets.TESTING_MONGO_PASS }}"
          --set-env-vars "MONGO_URL=${{ secrets.MONGO_URL }}"
          --set-env-vars "MONGO_DB=${{ secrets.TESTING_MONGO_DB }}"
          --set-env-vars "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}"
          --set-env-vars "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}"
          --set-env-vars "SERVER_URL=https://testing-zcgw6ooqia-uc.a.run.app"
          --set-env-vars "CLIENT_URL=https://testing-zcgw6ooqia-uc.a.run.app"
          --set-env-vars "SESSION_SECRET=${{ secrets.SESSION_SECRET }}"


